# Generated by Django 6.0.3 on 2026-06-14 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionIdentityReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', models.JSONField(default=list, help_text='Serialised reference face embedding (list of floats).')),
                ('backend', models.CharField(default='stub', help_text='Pipeline backend that produced the embedding (stub/playground).', max_length=32)),
                ('dims', models.PositiveIntegerField(default=0, help_text='Embedding dimensionality.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_reference', to='exam_sessions.examsession')),
            ],
            options={
                'verbose_name': 'Session Identity Reference',
                'verbose_name_plural': 'Session Identity References',
                'db_table': 'monitoring_identity_reference',
            },
        ),
    ]
