# Generated by Django 6.0.3 on 2026-06-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionidentityreference',
            name='backend',
            field=models.CharField(default='stub', help_text='Pipeline backend that produced the embedding (production/stub/disabled).', max_length=32),
        ),
    ]
