"""Generate UTAUT testing pack under docs/testing(UTAUT)/ from UTAUT chap 7.pdf structure.

Run from repo root:
  python "docs/testing(UTAUT)/scripts/bootstrap_utaut_content.py"
"""

from __future__ import annotations

import json
from pathlib import Path

BASE = Path(__file__).resolve().parents[1]
FW = BASE / "framework-data"
INST = BASE / "instrument-data"
RESP = BASE / "respondent-data"
CH = BASE / "chapter-data"
RD = BASE / "results-data"
SCRIPTS = BASE / "scripts"
DOCS = BASE / "documents"

PROJECT = "OSAS Web-Based Student Management System (WBSMS)"
INSTITUTION = "Legacy College of Compostela"
OFFICE = "Office of Student Affairs and Services (OSAS)"
N = 50
DATE = "2026-05-15"
SOURCE_PDF = "docs/overview/documents/UTAUT chap 7.pdf"


def w(path: Path, data: dict | list) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


SURVEY_ITEMS = [
    {"item_id": "PE1", "construct": "PE", "number": 1, "statement": "The system helps me accomplish my work tasks more quickly."},
    {"item_id": "PE2", "construct": "PE", "number": 2, "statement": "Using the system increases my productivity."},
    {"item_id": "PE3", "construct": "PE", "number": 3, "statement": "The system provides information that is useful and accurate for my work."},
    {"item_id": "PE4", "construct": "PE", "number": 4, "statement": "The outputs generated by the system meet my job requirements."},
    {"item_id": "PE5", "construct": "PE", "number": 5, "statement": "Overall, the system improves the quality of my work."},
    {"item_id": "EE6", "construct": "EE", "number": 6, "statement": "The interface of the system is clear and easy to understand."},
    {"item_id": "EE7", "construct": "EE", "number": 7, "statement": "It was easy to learn how to use the system."},
    {"item_id": "EE8", "construct": "EE", "number": 8, "statement": "I can use the system without needing much assistance."},
    {"item_id": "EE9", "construct": "EE", "number": 9, "statement": "The system's navigation is logical and straightforward."},
    {"item_id": "EE10", "construct": "EE", "number": 10, "statement": "The system requires minimal effort to operate."},
    {"item_id": "SI11", "construct": "SI", "number": 11, "statement": "My supervisors/instructors encourage me to use the system."},
    {"item_id": "SI12", "construct": "SI", "number": 12, "statement": "My colleagues/classmates use and recommend the system."},
    {"item_id": "SI13", "construct": "SI", "number": 13, "statement": "The institution supports the use of this system for official tasks."},
    {"item_id": "SI14", "construct": "SI", "number": 14, "statement": "People who are important to me think I should use the system."},
    {"item_id": "SI15", "construct": "SI", "number": 15, "statement": "Using the system is considered a standard practice in my organization."},
    {"item_id": "FC16", "construct": "FC", "number": 16, "statement": "I have the necessary equipment (device, internet) to use the system."},
    {"item_id": "FC17", "construct": "FC", "number": 17, "statement": "Technical support is available when I encounter problems with the system."},
    {"item_id": "FC18", "construct": "FC", "number": 18, "statement": "The system is compatible with the devices and tools I commonly use."},
    {"item_id": "FC19", "construct": "FC", "number": 19, "statement": "I have received sufficient training or orientation to use the system."},
    {"item_id": "FC20", "construct": "FC", "number": 20, "statement": "When I encounter difficulties, help is readily available."},
    {"item_id": "BI21", "construct": "BI", "number": 21, "statement": "I intend to continue using this system in the future."},
    {"item_id": "BI22", "construct": "BI", "number": 22, "statement": "I plan to use the system more frequently than I currently do."},
    {"item_id": "BI23", "construct": "BI", "number": 23, "statement": "I would recommend this system to others."},
    {"item_id": "BI24", "construct": "BI", "number": 24, "statement": "Given the chance, I would choose to use this system over alternatives."},
    {"item_id": "BI25", "construct": "BI", "number": 25, "statement": "I am satisfied with the system and would support its continued use."},
]

CONSTRUCTS = [
    {"no": 1, "code": "PE", "name": "Performance Expectancy", "definition": "The degree to which the user believes that using the system will help them achieve gains in job performance.", "measurement_focus": "Usefulness, efficiency, productivity improvement in OSAS tasks"},
    {"no": 2, "code": "EE", "name": "Effort Expectancy", "definition": "The degree of ease associated with the use of the system.", "measurement_focus": "Ease of use, learnability, clarity of interface"},
    {"no": 3, "code": "SI", "name": "Social Influence", "definition": "The degree to which the user perceives that important others believe they should use the system.", "measurement_focus": "Peer influence, supervisory support, institutional norms"},
    {"no": 4, "code": "FC", "name": "Facilitating Conditions", "definition": "The degree to which the user believes that organizational and technical infrastructure exists to support system use.", "measurement_focus": "Technical support, device/internet availability, training"},
    {"no": 5, "code": "BI", "name": "Behavioral Intention", "definition": "The extent to which users intend to use the system in the future.", "measurement_focus": "Willingness to recommend, continued use intention"},
]

LIKERT = [
    {"scale": "Strongly Agree", "value": 5, "wm_range": "4.50 – 5.00", "interpretation": "Excellent / Outstanding"},
    {"scale": "Agree", "value": 4, "wm_range": "3.50 – 4.49", "interpretation": "Very Satisfactory"},
    {"scale": "Neutral", "value": 3, "wm_range": "2.50 – 3.49", "interpretation": "Satisfactory"},
    {"scale": "Disagree", "value": 2, "wm_range": "1.50 – 2.49", "interpretation": "Unsatisfactory"},
    {"scale": "Strongly Disagree", "value": 1, "wm_range": "1.00 – 1.49", "interpretation": "Poor / Needs Improvement"},
]

# Illustrative item stats from UTAUT chap 7.pdf (replace via compute_utaut_statistics.py)
ITEM_STATS_PE = [
    ("PE1", "The system helps me accomplish my work tasks more quickly.", "4.72", "0.41", "Excellent"),
    ("PE2", "Using the system increases my productivity.", "4.68", "0.47", "Excellent"),
    ("PE3", "The system provides useful and accurate information for my work.", "4.58", "0.55", "Excellent"),
    ("PE4", "The outputs generated by the system meet my job requirements.", "4.62", "0.49", "Excellent"),
    ("PE5", "Overall, the system improves the quality of my work.", "4.74", "0.38", "Excellent"),
]

CONSOLIDATED = [
    ("1", "Performance Expectancy (PE)", "4.67", "0.46", "Excellent"),
    ("2", "Effort Expectancy (EE)", "4.54", "0.51", "Excellent"),
    ("3", "Social Influence (SI)", "4.38", "0.59", "Very Satisfactory"),
    ("4", "Facilitating Conditions (FC)", "4.42", "0.57", "Very Satisfactory"),
    ("5", "Behavioral Intention (BI)", "4.61", "0.48", "Excellent"),
    ("", "OVERALL WEIGHTED MEAN", "4.52", "0.52", "EXCELLENT"),
]

PEARSON = [
    ("Performance Expectancy (PE)", "0.812", "0.001", "p < 0.05", "Reject H₀"),
    ("Effort Expectancy (EE)", "0.784", "0.001", "p < 0.05", "Reject H₀"),
    ("Social Influence (SI)", "0.691", "0.002", "p < 0.05", "Reject H₀"),
    ("Facilitating Conditions (FC)", "0.703", "0.001", "p < 0.05", "Reject H₀"),
]

RESPONDENT_PROFILE = [
    ("User Role", "Students (End-users)", 12, 13, 25),
    ("User Role", "Student Assistants", 4, 3, 7),
    ("User Role", "OSAS Faculty", 5, 5, 10),
    ("User Role", "System Administrators", 4, 4, 8),
    ("Age Group", "18–25 years old", 14, 16, 30),
    ("Age Group", "26–35 years old", 7, 6, 13),
    ("Age Group", "36 years old and above", 4, 3, 7),
    ("Tech Proficiency", "Beginner", 5, 6, 11),
    ("Tech Proficiency", "Intermediate", 12, 14, 26),
    ("Tech Proficiency", "Advanced", 8, 5, 13),
]


def build_item_stats_table(construct: str, illustrative_wm: str) -> dict:
    items = [i for i in SURVEY_ITEMS if i["construct"] == construct]
    rows = []
    for it in items:
        if construct == "PE":
            match = next((r for r in ITEM_STATS_PE if r[0] == it["item_id"]), None)
            if match:
                rows.append(list(match))
                continue
        rows.append([it["item_id"], it["statement"], "[WM]", "[SD]", "[Interpretation]"])
    rows.append(["", f"Overall Weighted Mean ({construct})", illustrative_wm, "[SD]", "[Interpretation]"])
    return {
        "caption": f"Table 7.x. {construct} – Descriptive Statistics (n = {N})",
        "headers": ["Item", "Statement", "Weighted Mean", "Std. Dev.", "Interpretation"],
        "rows": rows,
        "note": "Replace with output from compute_utaut_statistics.py when raw responses are available.",
    }


def main() -> None:
    for d in [FW, INST, RESP, CH, RD / "evidence", DOCS]:
        d.mkdir(parents=True, exist_ok=True)
    (RD / "evidence" / ".gitkeep").write_text("", encoding="utf-8")
    (DOCS / ".gitkeep").write_text("", encoding="utf-8")

    w(
        FW / "manifest.json",
        {
            "title": "UTAUT framework reference data",
            "source": SOURCE_PDF,
            "files": ["01_utaut_theory_reference.json", "02_likert_scale_legend.json", "03_analysis_methods.json"],
        },
    )

    w(
        FW / "01_utaut_theory_reference.json",
        {
            "model": "Unified Theory of Acceptance and Use of Technology (UTAUT)",
            "citation": "Venkatesh, V., Morris, M. G., Davis, G. B., & Davis, F. D. (2003). User acceptance of information technology: Toward a unified view. MIS Quarterly, 27(3), 425–478.",
            "application": f"User acceptance evaluation of {PROJECT} at {INSTITUTION}",
            "constructs": CONSTRUCTS,
            "dependent_variable_for_correlation": "Behavioral Intention (BI)",
            "independent_variables_for_correlation": ["PE", "EE", "SI", "FC"],
            "hypotheses": [
                {"id": "H1", "text": "Performance Expectancy is positively correlated with Behavioral Intention."},
                {"id": "H2", "text": "Effort Expectancy is positively correlated with Behavioral Intention."},
                {"id": "H3", "text": "Social Influence is positively correlated with Behavioral Intention."},
                {"id": "H4", "text": "Facilitating Conditions is positively correlated with Behavioral Intention."},
            ],
        },
    )

    w(FW / "02_likert_scale_legend.json", {"table_7_8": {"caption": "Table 7.8. Likert Scale Interpretation Legend", "rows": LIKERT}})

    w(
        FW / "03_analysis_methods.json",
        {
            "descriptive": {
                "metrics": ["weighted_mean", "standard_deviation"],
                "interpretation": "Table 7.8 legend (Reyes & Santos, 2022; Dumaliang & Ramos, 2021)",
            },
            "inferential": {
                "test": "Pearson product-moment correlation",
                "pairs": "Each of PE, EE, SI, FC vs overall BI construct mean per respondent",
                "alpha": 0.05,
                "null_hypothesis": "No significant relationship between construct and Behavioral Intention",
            },
            "tools": {
                "recommended": ["Microsoft Excel", "SPSS", "Python (scripts/compute_utaut_statistics.py)"],
                "formula_weighted_mean": "WM = Σ(value × count) / n for each item or construct",
            },
        },
    )

    w(
        INST / "manifest.json",
        {
            "title": "UTAUT survey instrument",
            "instrument_title": "USER ACCEPTANCE TESTING (UAT) SURVEY — UTAUT",
            "likert": "5 = SA, 4 = A, 3 = N, 2 = D, 1 = SD",
            "files": ["01_survey_questionnaire.json", "02_osas_official_questionnaires.json"],
        },
    )

    w(
        INST / "01_survey_questionnaire.json",
        {
            "system": PROJECT,
            "institution": INSTITUTION,
            "instructions": "Please rate each statement based on your experience with the WBSMS. Use the 5-point Likert scale.",
            "likert_scale": LIKERT,
            "parts": [
                {
                    "part": "I",
                    "title": "Respondent Information",
                    "fields": [
                        "name_optional",
                        "date",
                        "role_position",
                        "department_section",
                        "age",
                        "gender",
                        "tech_proficiency",
                    ],
                },
                {
                    "part": "II",
                    "title": "Performance Expectancy (PE)",
                    "construct_code": "PE",
                    "intro": "The system helps me accomplish my tasks more effectively.",
                    "items": [i for i in SURVEY_ITEMS if i["construct"] == "PE"],
                },
                {
                    "part": "III",
                    "title": "Effort Expectancy (EE)",
                    "construct_code": "EE",
                    "intro": "The system is easy to use and learn.",
                    "items": [i for i in SURVEY_ITEMS if i["construct"] == "EE"],
                },
                {
                    "part": "IV",
                    "title": "Social Influence (SI)",
                    "construct_code": "SI",
                    "intro": "People around me support my use of the system.",
                    "items": [i for i in SURVEY_ITEMS if i["construct"] == "SI"],
                },
                {
                    "part": "V",
                    "title": "Facilitating Conditions (FC)",
                    "construct_code": "FC",
                    "intro": "Resources and support are available to help me use the system.",
                    "items": [i for i in SURVEY_ITEMS if i["construct"] == "FC"],
                },
                {
                    "part": "VI",
                    "title": "Behavioral Intention (BI)",
                    "construct_code": "BI",
                    "intro": "I intend to continue using the system in the future.",
                    "items": [i for i in SURVEY_ITEMS if i["construct"] == "BI"],
                },
                {
                    "part": "VII",
                    "title": "Open-Ended Questions",
                    "questions": [
                        "What feature of the system do you find most useful? Why?",
                        "What difficulties or challenges did you encounter while using the system?",
                        "What improvements or additional features would you suggest for the system?",
                        "How has the system affected your workflow or daily tasks?",
                        "Any other comments, suggestions, or feedback?",
                    ],
                },
            ],
        },
    )

    w(
        INST / "02_osas_official_questionnaires.json",
        {
            "note": "Official Word questionnaires maintained separately; align item numbering with 01_survey_questionnaire.json",
            "files": [
                "docs/overview/documents/OSAS_sys_Questionnaire(student).docx",
                "docs/overview/documents/OSAS_sys_Questionnaire(admin).docx",
            ],
            "appendix_reference": "Appendix H — Accomplished Survey Questionnaire (thesis)",
        },
    )

    w(
        RESP / "01_uat_respondent_profile.json",
        {
            "caption": "Table 7.7. Profile of UAT Respondents",
            "sample_size": N,
            "headers": ["Category", "Group", "Male", "Female", "Total"],
            "rows": [{"category": r[0], "group": r[1], "male": r[2], "female": r[3], "total": r[4]} for r in RESPONDENT_PROFILE],
            "note": "Update counts from actual survey distribution before final thesis submission.",
        },
    )

    w(
        RESP / "02_sampling_plan.json",
        {
            "uat_context": "Conducted after WBSMS deployment; respondents use system then complete UTAUT survey",
            "target_n": N,
            "role_distribution_target": {
                "students": 25,
                "student_assistants": 7,
                "faculty": 10,
                "administrators": 8,
            },
            "eligibility": [
                "Used WBSMS at least once in assigned role",
                "Completed Parts I–VI of survey",
                "Synthetic/test accounts allowed for course demo if disclosed",
            ],
        },
    )

    w(
        CH / "manifest.json",
        {
            "title": "Thesis Chapter 7 — UTAUT sections (7.6–7.8)",
            "target": "docs/overview/documents/OSAS_sys_document(WBSMS).docx",
            "related_pack": "docs/testing/ (functional test cases)",
            "files": [
                "07_6_utaut_framework.json",
                "07_7_survey_questionnaire.json",
                "07_8_data_analysis.json",
                "full_chapter_7_utaut_export.json",
            ],
        },
    )

    w(
        CH / "07_6_utaut_framework.json",
        {
            "section_id": "7.6",
            "title": "UTAUT Framework and User Acceptance Evaluation",
            "paragraphs": [
                f"The researchers used the UTAUT model (Venkatesh et al., 2003) to evaluate acceptance of the {PROJECT} at {INSTITUTION}.",
                f"User Acceptance Testing involved {N} respondents who were actual users of the deployed WBSMS.",
            ],
            "table_7_6_constructs": {
                "caption": "Table 7.6. UTAUT Constructs and Definitions",
                "headers": ["No.", "Construct", "Definition", "Measurement Focus"],
                "rows": [[c["no"], f"{c['name']} ({c['code']})", c["definition"], c["measurement_focus"]] for c in CONSTRUCTS],
            },
            "table_7_7_respondents": {
                "caption": "Table 7.7. Profile of UAT Respondents",
                "headers": ["Category", "Group", "Male", "Female", "Total"],
                "rows": [[r[0], r[1], r[2], r[3], r[4]] for r in RESPONDENT_PROFILE],
            },
        },
    )

    w(
        CH / "07_7_survey_questionnaire.json",
        {
            "section_id": "7.7",
            "title": "UTAUT Survey Questionnaire",
            "reference_instrument": "instrument-data/01_survey_questionnaire.json",
            "paragraphs": [
                "The survey instrument follows UTAUT chap 7.pdf with OSAS-specific deployment context.",
                "Twenty-five Likert items and five open-ended questions were administered after hands-on system use.",
            ],
        },
    )

    w(
        CH / "07_8_data_analysis.json",
        {
            "section_id": "7.8",
            "title": "Data Analysis and Interpretation",
            "sample_size": N,
            "table_7_8_likert": {"caption": "Table 7.8. Likert Scale Interpretation Legend", "rows": LIKERT},
            "table_7_9_pe": build_item_stats_table("PE", "4.67"),
            "table_7_10_consolidated": {
                "caption": f"Table 7.10. Consolidated UTAUT Evaluation Results (n = {N})",
                "headers": ["No.", "UTAUT Construct", "Weighted Mean", "Std. Deviation", "Descriptive Rating"],
                "rows": [list(r) for r in CONSOLIDATED],
            },
            "table_7_11_pearson": {
                "caption": "Table 7.11. Pearson's r Correlation – UTAUT Constructs vs. Behavioral Intention",
                "headers": ["UTAUT Construct", "Pearson's r", "p-value", "Significance", "Decision"],
                "rows": [list(r) for r in PEARSON],
                "note": "H₀: no significant relationship at α = 0.05",
            },
            "discussion_paragraphs": [
                "The consolidated UTAUT evaluation yielded an overall weighted mean of 4.52 (Excellent), indicating strong acceptance of the WBSMS.",
                "Performance Expectancy (WM = 4.67) was highest, suggesting users perceive strong task benefits in profiling, violations, and reporting.",
                "Pearson's r showed significant positive relationships between PE, EE, SI, FC and Behavioral Intention (all p < 0.05).",
            ],
            "data_status": "illustrative_from_utaut_chap_7_pdf",
        },
    )

    w(
        CH / "full_chapter_7_utaut_export.json",
        {
            "description": "Merged 7.6–7.8 for insertion into thesis or OSAS_chapters_7_10_content.json",
            "source_pdf": SOURCE_PDF,
            "sections": ["07_6_utaut_framework.json", "07_7_survey_questionnaire.json", "07_8_data_analysis.json"],
            "cross_reference": "docs/overview/documents/OSAS_chapters_7_10_content.json chapter 7 blocks 7.6–7.8",
        },
    )

    # Raw response template
    template_row = {"respondent_id": "R001", "role": "student", "gender": "female", "age_group": "18-25", "tech_proficiency": "intermediate"}
    for it in SURVEY_ITEMS:
        template_row[it["item_id"]] = 5

    w(
        RD / "manifest.json",
        {
            "title": "UTAUT results-data hub",
            "workflow": [
                "1. Collect accomplished questionnaires → scan to evidence/",
                "2. Encode Likert scores in raw_responses.json",
                "3. Run compute_utaut_statistics.py",
                "4. Run sync_results_to_chapter_data.py",
                "5. Optional: generate_documents.py for Word exports",
            ],
            "files": [
                "raw_responses.json",
                "computed_descriptive_stats.json",
                "computed_pearson_correlation.json",
                "summary_for_thesis.json",
            ],
        },
    )

    w(
        RD / "raw_responses.json",
        {
            "description": "One object per respondent. Likert values 1–5. Replace illustrative data with actual encoded surveys.",
            "respondents": [],
            "template_row": template_row,
        },
    )

    w(
        RD / "computed_descriptive_stats.json",
        {
            "description": "Generated by compute_utaut_statistics.py",
            "sample_size": N,
            "status": "illustrative_placeholder",
            "by_item": {r[0]: {"weighted_mean": float(r[2]), "std_dev": float(r[3]), "interpretation": r[4]} for r in ITEM_STATS_PE},
            "by_construct": {
                "PE": {"weighted_mean": 4.67, "std_dev": 0.46, "interpretation": "Excellent"},
                "EE": {"weighted_mean": 4.54, "std_dev": 0.51, "interpretation": "Excellent"},
                "SI": {"weighted_mean": 4.38, "std_dev": 0.59, "interpretation": "Very Satisfactory"},
                "FC": {"weighted_mean": 4.42, "std_dev": 0.57, "interpretation": "Very Satisfactory"},
                "BI": {"weighted_mean": 4.61, "std_dev": 0.48, "interpretation": "Excellent"},
                "OVERALL": {"weighted_mean": 4.52, "std_dev": 0.52, "interpretation": "EXCELLENT"},
            },
        },
    )

    w(
        RD / "computed_pearson_correlation.json",
        {
            "description": "Pearson r: each construct mean vs respondent BI mean",
            "rows": [
                {"construct": r[0], "pearson_r": float(r[1]), "p_value": float(r[2]), "significance": r[3], "decision": r[4]}
                for r in PEARSON
            ],
            "note": "Recompute from raw_responses.json using scipy or Excel CORREL",
        },
    )

    w(
        RD / "summary_for_thesis.json",
        {
            "overall_weighted_mean": 4.52,
            "overall_interpretation": "EXCELLENT",
            "highest_construct": {"code": "PE", "weighted_mean": 4.67},
            "lowest_construct": {"code": "SI", "weighted_mean": 4.38},
            "all_hypotheses_supported": True,
        },
    )

    w(
        RD / "source_map.json",
        {
            "base": "docs/testing(UTAUT)",
            "source_pdf": SOURCE_PDF,
            "framework_data": "framework-data/",
            "instrument_data": "instrument-data/",
            "chapter_data": "chapter-data/",
            "functional_testing_pack": "docs/testing/",
            "thesis_chapter_json": "docs/overview/documents/OSAS_chapters_7_10_content.json",
        },
    )

    print("OK: testing(UTAUT) content generated at", BASE)


if __name__ == "__main__":
    main()
