# Generated by Django 6.0.3 on 2026-03-23 12:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Exam title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed exam description')),
                ('instructions', models.TextField(blank=True, help_text='Exam instructions for examinees')),
                ('duration_minutes', models.IntegerField(default=120, help_text='Exam duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_questions', models.IntegerField(default=0, help_text='Total number of questions (auto-calculated)', validators=[django.core.validators.MinValueValidator(0)])),
                ('passing_score', models.IntegerField(default=40, help_text='Minimum passing percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', help_text='Exam status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created this exam', on_delete=django.db.models.deletion.PROTECT, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exams_exam',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question content')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay')], default='multiple_choice', help_text='Type of question', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='JSON array of answer options for multiple choice')),
                ('correct_answer', models.TextField(help_text='The correct answer or answer key')),
                ('points', models.IntegerField(default=1, help_text='Points awarded for correct answer', validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.IntegerField(default=0, help_text='Display order within exam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(help_text='Exam this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'exams_question',
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status', '-created_at'], name='exams_exam_status_a8aba3_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['created_by'], name='exams_exam_created_32462e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'order'], name='exams_quest_exam_id_4ac027_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam', 'order')},
        ),
    ]
