# Generated by Django 6.0.3 on 2026-06-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_scheduling_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exam',
            new_name='exams_exam_exam_co_1362ff_idx',
            old_name='exams_exam_exam_co_idx',
        ),
        migrations.RenameIndex(
            model_name='exam',
            new_name='exams_exam_availab_35af7e_idx',
            old_name='exams_exam_avail_idx',
        ),
    ]
