# Generated by Django 6.0.3 on 2026-07-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_exam_refactor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='examassignment',
            new_name='exams_assig_exam_id_df52fc_idx',
            old_name='exams_assig_exam_id_idx',
        ),
        migrations.RenameIndex(
            model_name='examassignment',
            new_name='exams_assig_user_id_656e78_idx',
            old_name='exams_assig_user_id_idx',
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_practice',
            field=models.BooleanField(default=False, help_text='Practice exams allow unlimited attempts and optional answer reveal'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='max_tab_switches',
            field=models.PositiveIntegerField(blank=True, help_text='Optional limit on tab switches before flagging (null = no limit)', null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='requires_assignment',
            field=models.BooleanField(default=False, help_text='When true, only assigned candidates may start this exam'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='results_release_at',
            field=models.DateTimeField(blank=True, help_text='When examinees may view results (null = immediate on submit)', null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='show_correct_answers',
            field=models.CharField(choices=[('never', 'Never'), ('after_release', 'After results release'), ('immediately', 'Immediately after submit')], default='never', help_text='When examinees may see correct answers', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='shuffle_options',
            field=models.BooleanField(default=False, help_text='When enabled, multiple-choice options are shuffled per attempt'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='unanswered_counts_as_wrong',
            field=models.BooleanField(default=True, help_text='When true, unanswered questions score zero toward the total'),
        ),
        migrations.AlterField(
            model_name='examsection',
            name='questions_per_page',
            field=models.PositiveIntegerField(default=1, help_text='1 = one question per page; 0 = show all questions in section'),
        ),
        migrations.AlterField(
            model_name='question',
            name='acceptable_answers',
            field=models.JSONField(blank=True, default=list, help_text='Additional acceptable answers for short-answer auto-grade'),
        ),
        migrations.AlterField(
            model_name='question',
            name='shuffle_options_override',
            field=models.BooleanField(blank=True, help_text='Override exam-level option shuffle (null = inherit)', null=True),
        ),
        migrations.AlterField(
            model_name='questionpool',
            name='draw_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of questions drawn from this pool per attempt'),
        ),
    ]
