# Generated by Django 6.0.3 on 2026-08-13 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_rename_exams_assig_exam_id_idx_exams_assig_exam_id_df52fc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamApprovalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Submitted for review'), ('approve', 'Approved'), ('reject', 'Rejected')], max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exams_approval_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='approval_status',
            field=models.CharField(choices=[('not_submitted', 'Not submitted'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', help_text='Level 0/1 approval chain state - must be APPROVED before publish', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='rejection_note',
            field=models.TextField(blank=True, default='', help_text='Reviewer feedback when approval_status is REJECTED'),
        ),
        migrations.AddField(
            model_name='exam',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Program head / admin who last approved or rejected this exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who last submitted this exam for approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this exam', on_delete=django.db.models.deletion.PROTECT, related_name='created_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['approval_status'], name='exams_exam_approva_27648d_idx'),
        ),
        migrations.AddField(
            model_name='examapprovalevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_approval_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examapprovalevent',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_events', to='exams.exam'),
        ),
    ]
