# Generated by Django 6.0.3 on 2026-08-19 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_exam_approval_chain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam category',
                'verbose_name_plural': 'Exam categories',
                'db_table': 'exams_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Every department this exam is assigned to, including the home department. Lets shared/general-ed exams be discovered from more than one department without giving up the single home department the exam code is generated from.', related_name='shared_exams', to='exams.department'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Home department that owns this exam (used for auto-generated codes)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='exams.department'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of answer options for multiple choice. Each item is {"text": str, "image": str | null} - image is a media URL, set via the option-image upload endpoint, for abstract/psychological items that need image-based options rather than plain text.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Guidance content classification (psychological, behavioral, ...), independent of department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='exams.examcategory'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['category'], name='exams_exam_categor_1e6004_idx'),
        ),
    ]
