# Generated by Django 6.0.3 on 2026-08-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_seed_categories_backfill_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassignment',
            name='seat_label',
            field=models.CharField(blank=True, default='', help_text="Physical seat/room/station identifier, so a proctor can find a flagged examinee in person rather than only in a list row (Directive Area 04 - 'proctor locator').", max_length=32),
        ),
    ]
