# Generated by Django 6.0.3 on 2026-09-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_renormalize_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='disable_copy_paste',
            field=models.BooleanField(default=False, help_text='When enabled, copy, cut, and paste are blocked while examinees take the exam'),
        ),
    ]
