# Generated by Django 6.0.3 on 2026-10-02 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_exam_disable_copy_paste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examapprovalevent',
            index=models.Index(fields=['exam', '-created_at'], name='exams_appro_exam_id_585758_idx'),
        ),
    ]
