/**
 * Icon barrel — Phosphor Icons, re-exported under the identifier names the
 * app already used for Lucide (Home, Eye, Users, AlertCircle, ...), so call
 * sites (`<Home className="..." />`) keep working unchanged; only the import
 * source moves to `@/shared/icons`. Where two old names mapped to one
 * Phosphor glyph (ChevronRight/ChevronRightIcon -> CaretRight), both aliases
 * are exported pointing at the same component.
 *
 * `AppIcon` replaces the old `LucideIcon` prop type for components that
 * accept an icon component as a prop.
 */

export type { Icon as AppIcon, IconProps as AppIconProps, IconWeight } from "@phosphor-icons/react";

export {
  Pulse as Activity,
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowRight,
  Medal as Award,
  ChartBar as BarChart3,
  Bell,
  BookOpen,
  Brain,
  Buildings as Building2,
  Calendar,
  CalendarCheck,
  Camera,
  CameraSlash as CameraOff,
  CheckCircle,
  CheckCircle as CheckCircle2,
  Check as CheckIcon,
  CaretDown as ChevronDown,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeft,
  CaretLeft as ChevronLeftIcon,
  CaretRight as ChevronRight,
  CaretRight as ChevronRightIcon,
  CaretUp as ChevronUp,
  CaretUp as ChevronUpIcon,
  Circle,
  Circle as CircleIcon,
  CheckSquare as ClipboardCheck,
  ClipboardText as ClipboardList,
  Clock,
  Copy,
  ArrowElbowDownLeft as CornerDownLeft,
  ArrowElbowDownRight as CornerDownRight,
  ArrowElbowUpLeft as CornerUpLeft,
  ArrowElbowUpRight as CornerUpRight,
  Database,
  DownloadSimple as Download,
  Eye,
  EyeSlash as EyeOff,
  FileAudio,
  ClipboardText as FileCheck,
  FileImage,
  FileText,
  Flag,
  GraduationCap,
  DotsSixVertical as GripVertical,
  DotsSixVertical as GripVerticalIcon,
  House as Home,
  ImageSquare as ImagePlus,
  Tray as Inbox,
  Key as KeyRound,
  SquaresFour as LayoutDashboard,
  Lightbulb,
  ChartLine as LineChart,
  CircleNotch as Loader2,
  Lock,
  SignOut as LogOut,
  MapPin,
  List as Menu,
  Minus as MinusIcon,
  Moon,
  DotsThree as MoreHorizontal,
  DotsThree as MoreHorizontalIcon,
  CaretLineLeft as PanelLeftClose,
  SidebarSimple as PanelLeftIcon,
  CaretLineRight as PanelLeftOpen,
  PencilSimple as Pencil,
  Person as PersonStanding,
  PlayCircle,
  Plus,
  Power,
  Prohibit as PowerOff,
  Radio,
  ArrowsClockwise as RefreshCw,
  FloppyDisk as Save,
  ScanSmiley as ScanFace,
  MagnifyingGlass as Search,
  MagnifyingGlass as SearchIcon,
  PaperPlaneTilt as Send,
  Gear as Settings,
  ShieldWarning as ShieldAlert,
  ShieldCheck,
  ShieldSlash as ShieldOff,
  Sparkle as Sparkles,
  Sun,
  Target,
  Trash as Trash2,
  TrendUp as TrendingUp,
  UploadSimple as Upload,
  User,
  UserCheck,
  UserCircle,
  UserGear as UserCog,
  Users,
  VideoCamera as Video,
  X,
  XCircle,
  X as XIcon,
} from "@phosphor-icons/react";
