# Generated by Django 6.0.3 on 2026-05-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='authenticat_role_7fb088_idx',
            old_name='auth_user_role_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
