# Generated by Django 6.0.3 on 2026-10-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_otp_email_verification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='permissionchange',
            index=models.Index(fields=['target', 'permission', '-created_at'], name='authenticat_target__dbc5c7_idx'),
        ),
    ]
