# Generated by Django 6.0.3 on 2026-05-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alert',
            new_name='behavior_al_session_e63ccf_idx',
            old_name='behavior_al_session_4a1c9d_idx',
        ),
        migrations.RenameIndex(
            model_name='alert',
            new_name='behavior_al_resolve_3dac16_idx',
            old_name='behavior_al_resolve_2b7e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='behaviorlog',
            new_name='behavior_lo_session_670807_idx',
            old_name='behavior_lo_session_6e2e0a_idx',
        ),
        migrations.RenameIndex(
            model_name='behaviorlog',
            new_name='behavior_lo_event_t_bbe32d_idx',
            old_name='behavior_lo_event_t_8f3b2c_idx',
        ),
    ]
