# Generated by Django 6.0.3 on 2026-06-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0002_rename_behavior_al_session_4a1c9d_idx_behavior_al_session_e63ccf_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorlog',
            name='event_type',
            field=models.CharField(choices=[('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces'), ('looking_away', 'Looking Away'), ('bad_posture', 'Bad Posture'), ('object_detected', 'Object Detected'), ('identity_mismatch', 'Identity Mismatch')], max_length=32),
        ),
    ]
