# Generated by Django 6.0.3 on 2026-03-24 04:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the session started')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the exam was submitted', null=True)),
                ('time_remaining', models.IntegerField(default=0, help_text='Seconds remaining when submitted (for partial submissions)')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='in_progress', help_text='Current session status', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address for security tracking', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information', null=True)),
                ('total_score', models.IntegerField(blank=True, help_text='Total score achieved (calculated on submission)', null=True)),
                ('percentage_score', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage score (0-100)', max_digits=5, null=True)),
                ('passed', models.BooleanField(blank=True, help_text='Whether the examinee passed the exam', null=True)),
                ('exam', models.ForeignKey(help_text='The exam being taken', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='exams.exam')),
                ('user', models.ForeignKey(help_text='The examinee taking the exam', on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Session',
                'verbose_name_plural': 'Exam Sessions',
                'db_table': 'user_sessions_exam_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text='The answer provided by the examinee')),
                ('is_correct', models.BooleanField(default=False, help_text='Whether the answer matches the correct answer')),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent on this question in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('answered_at', models.DateTimeField(auto_now_add=True, help_text='When this answer was submitted')),
                ('flagged_for_review', models.BooleanField(default=False, help_text='Whether this response was flagged for manual review')),
                ('question', models.ForeignKey(help_text='The question being answered', on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='exams.question')),
                ('session', models.ForeignKey(help_text='The exam session this response belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exam_sessions.examsession')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
                'db_table': 'user_sessions_response',
                'ordering': ['session', 'question__order'],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('started', 'Session Started'), ('submitted', 'Session Submitted'), ('terminated', 'Session Terminated'), ('expired', 'Session Expired'), ('resumed', 'Session Resumed'), ('paused', 'Session Paused')], help_text='Type of session event', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the event occurred')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional event details (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address at time of event', null=True)),
                ('session', models.ForeignKey(help_text='The session this log entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='exam_sessions.examsession')),
            ],
            options={
                'verbose_name': 'Session Log',
                'verbose_name_plural': 'Session Logs',
                'db_table': 'user_sessions_session_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['exam', 'user'], name='user_sessio_exam_id_de8099_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['status', 'started_at'], name='user_sessio_status_96cc82_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['user', 'started_at'], name='user_sessio_user_id_7abf84_idx'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['in_progress'])), fields=('exam', 'user'), name='unique_active_session_per_exam_user'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['session', 'question'], name='user_sessio_session_b3ba2c_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['is_correct'], name='user_sessio_is_corr_13405c_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['flagged_for_review'], name='user_sessio_flagged_9695e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('session', 'question')},
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['session', 'timestamp'], name='user_sessio_session_0cb516_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['event_type', 'timestamp'], name='user_sessio_event_t_3d52e8_idx'),
        ),
    ]
