# Generated by Django 6.0.3 on 2026-07-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0005_exam_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='accommodation_extra_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Extra time granted for this attempt (minutes)'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='deadline_at',
            field=models.DateTimeField(blank=True, help_text='Server-computed deadline when the timed exam ends', null=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='option_order',
            field=models.JSONField(blank=True, help_text='Per-question shuffled option order: {question_id: [option, ...]}', null=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('setup', 'Setup'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='setup', help_text='Current session status', max_length=20),
        ),
        migrations.AlterField(
            model_name='response',
            name='autosaved_at',
            field=models.DateTimeField(blank=True, help_text='Last autosave timestamp during in-progress attempt', null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='points_awarded',
            field=models.IntegerField(blank=True, help_text='Manual override points (null = use auto-grade)', null=True),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='event_type',
            field=models.CharField(choices=[('started', 'Session Started'), ('submitted', 'Session Submitted'), ('terminated', 'Session Terminated'), ('expired', 'Session Expired'), ('resumed', 'Session Resumed'), ('paused', 'Session Paused'), ('exam_began', 'Exam Began'), ('tab_hidden', 'Tab Hidden'), ('tab_visible', 'Tab Visible'), ('fullscreen_exit', 'Fullscreen Exit')], help_text='Type of session event', max_length=20),
        ),
    ]
