# Generated by Django 6.0.3 on 2026-09-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0006_alter_examsession_accommodation_extra_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='ebi_average',
            field=models.FloatField(blank=True, help_text='Mean Exam Behavior Index (0-100) across all analyzed frames', null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='ebi_face_identity_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='ebi_face_presence_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='ebi_identity_sample_count',
            field=models.PositiveIntegerField(default=0, help_text='Frames where identity was evaluated (denominator for identity mean)'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='ebi_looking_away_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='ebi_sample_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of analyzed frames folded into the EBI running mean'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='ebi_upper_body_avg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
