# Generated by Django 6.0.3 on 2026-10-03 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_sessions", "0007_examsession_ebi_average_and_more"),
        ("exams", "0017_audit_trail_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="examsession",
            name="unique_active_session_per_user",
        ),
        migrations.AddField(
            model_name="examsession",
            name="pause_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional note from the proctor, shown to the examinee while paused",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="examsession",
            name="paused_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current pause began (null unless status is paused)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="examsession",
            name="paused_total_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total seconds this attempt has spent paused (finished pauses)",
            ),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("setup", "Setup"),
                    ("in_progress", "In Progress"),
                    ("paused", "Paused"),
                    ("pending_review", "Pending Review"),
                    ("completed", "Completed"),
                    ("terminated", "Terminated"),
                    ("expired", "Expired"),
                ],
                default="setup",
                help_text="Current session status",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="examsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["in_progress", "setup", "paused"])),
                fields=("user",),
                name="unique_active_session_per_user",
            ),
        ),
    ]
